### ISSUE TITLE
Useless code with stupid realization

### ISSUE THREAD

**Issue by TheSainEyereg** [Vazgen005/Paper-sami-auto-updater#1]
Your code is shit and making the same thing as these 3 lines of bash code:
```sh
ver='1.18.1'
rm paper*.jar
wget https://papermc.io/api/v1/paper/${ver}/latest/download
```

<details>
<summary>You should kill yourself now </summary>
<details><summary>Or you can learn more productive languages like C# or JS</summary>or lua (c)@Artemking4</details>
</details>

**Comment by Vazgen005** [comment]
Go Fuck Yourself OK?

**Comment by Eld3rly** [comment]
Elderly was here
